### ISSUE TITLE
Remove var_dump

### ISSUE THREAD

**Issue by tmuras** [DevEticeo/moodle-mod_glossaryfocus#7]
Most likely you do not want any var_dumps in the production code as they may expose sensitive information. I'd suggest to remove:
https://github.com/DevEticeo/moodle-mod_glossaryfocus/blob/main/lib.php#L55

**Comment by DevEticeo** [comment]
Hi Tomasz, 
Thank you very much for your comment, indeed it's not great, we have corrected this :)
